## Creating Numpy array

In [3]:
import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# 2d array

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
# 3D array

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(c)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
#dtype

d = np.array([1,2,3], dtype = float)
print(d)

[1. 2. 3.]


In [2]:
# arange
import numpy as np
 
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.arange(1,21,4)

array([ 1,  5,  9, 13, 17])

In [4]:
# reshape

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [5]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [12]:
#np.ones


np.ones((3,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
#np.zeros

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
#np.random

np.random.random((3,4))

array([[0.61221817, 0.91246878, 0.60770786, 0.34911172],
       [0.81329249, 0.64630657, 0.98370739, 0.6527404 ],
       [0.39518481, 0.66656992, 0.84202298, 0.52141464]])

In [16]:
#np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [17]:
#np.identity

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 2. Array Attributes

In [18]:
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [25]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [27]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
#ndim -> dimension of the array
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
#shape  -> shape of the array

print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
#size -> no of items 

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [23]:
# itemsize -> memory space each item takes

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [29]:
#dtype -> datatype of the array

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


## 3. Changing the datatype 

In [30]:
#astype

a3.dtype

dtype('int64')

In [32]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## 4. Array Operations

In [33]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [34]:
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
print(a2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [36]:
# Scalar operations

#arithemetic operations
a1 +2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [37]:
a2 ** 2

array([[144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [39]:
# relational operations
a2 > 5


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
# vector operations

# arithemetic

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [42]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

## 5. Array functions

In [43]:
a1  =  np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[62., 80., 73.],
       [86., 32., 41.],
       [70., 13., 90.]])

In [50]:
# max/min/sum/prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

90.0
13.0
547.0
3345959844864000.0


In [ ]:
# rowise max

np.max(a1,axis = 1)

# columnwise min

np.min(a1, axis = 0)

array([62., 13., 41.])

In [54]:
# mean/median/std/var

np.mean(a1,axis = 0)

array([72.66666667, 41.66666667, 68.        ])

In [55]:
np.median(a1)

np.float64(70.0)

In [56]:
np.std(a1)

np.float64(24.938937773769567)

In [57]:
np.var(a1)

np.float64(621.9506172839506)

In [58]:
# trignometric functions

np.sin(a1)

array([[-0.7391807 , -0.99388865, -0.67677196],
       [-0.92345845,  0.55142668, -0.15862267],
       [ 0.77389068,  0.42016704,  0.89399666]])

In [59]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [60]:
# log and exponents

a1

array([[62., 80., 73.],
       [86., 32., 41.],
       [70., 13., 90.]])

In [61]:
np.log(a1)

array([[4.12713439, 4.38202663, 4.29045944],
       [4.4543473 , 3.4657359 , 3.71357207],
       [4.24849524, 2.56494936, 4.49980967]])

In [62]:
np.exp(a1)

array([[8.43835667e+26, 5.54062238e+34, 5.05239363e+31],
       [2.23524660e+37, 7.89629602e+13, 6.39843494e+17],
       [2.51543867e+30, 4.42413392e+05, 1.22040329e+39]])

In [67]:
# round/floor/ceil

np.floor(np.random.rand(2,3)*100)

array([[70., 28., 56.],
       [ 0., 68., 94.]])

## 6. Indexing/slicing

In [72]:
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1,a2,a3, sep ='\n\n')


[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [73]:
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
#accessing 6 form a2
a2[1][2]    # -> a2[row][column]  for 2D

np.float64(6.0)

In [76]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [78]:
#to access 5 form a3 
a3[1][0][1]  # -> a3[pos of 2D array in which item exists][row][colum]

np.int64(5)

In [79]:
#slicing

print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a1[2:-1:2]  # -> same as python list

array([2, 4, 6, 8], dtype=int32)

In [84]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# 5 6 9 10
a2[1:,1:3]

array([[ 5.,  6.],
       [ 9., 10.]])

In [ ]:
# 0 3 8 11
a2[::2,::3]

array([[ 0.,  3.],
       [ 8., 11.]])

In [94]:
# 1 3 9 11

a2[::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [95]:
# 4 7
a2[1,::3]

array([4., 7.])

In [ ]:
# 1 2 3 5 6 7
a2[0:2,1:]

array([[1., 2., 3.],
       [5., 6., 7.]])

In [99]:
# 3D case
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [103]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [104]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
# 3 4 5
a3[0,1,:]

array([3, 4, 5])

In [ ]:
# 10 13 16
a3[1,:,1]

array([10, 13, 16])

In [ ]:
# 22 23 25 26
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [113]:
# 0 2 18 20

a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## 7. iterating

In [117]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

for i in a2:
    print(i)  # -> 1 row at a time in 2D

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [ ]:
a3

for i in a3:
    print(i)  # ->2D array at a time 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
# nditer converts the array in 1D and prints each item

for i in np.nditer(a3):  
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## 8. Reshaping

In [ ]:
# reshape  -> changes the shape of the array. Used earlier


In [ ]:
# Transpose
np.transpose(a2)
a2.T  # same

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [125]:
#ravel -> converts ndarray to 1D array

a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## 9. Stacking

In [ ]:
# horizontal stacking -> add columns
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hstack((a4,a5))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# vertical Stacking -> add rows
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## 10. Splitting

In [133]:
# horizontal spliting
arr = np.hstack((a4,a5))
arr

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# horizontal splitting -> splits columns
np.hsplit(arr,2)   # -> a4 in 2 parts

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [137]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# vertical splitting  -> split rows
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]