## Creating Numpy array

In [3]:
import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# 2d array

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
# 3D array

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(c)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
#dtype

d = np.array([1,2,3], dtype = float)
print(d)

[1. 2. 3.]


In [2]:
# arange
import numpy as np
 
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.arange(1,21,4)

array([ 1,  5,  9, 13, 17])

In [4]:
# reshape

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [5]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [12]:
#np.ones


np.ones((3,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
#np.zeros

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
#np.random

np.random.random((3,4))

array([[0.61221817, 0.91246878, 0.60770786, 0.34911172],
       [0.81329249, 0.64630657, 0.98370739, 0.6527404 ],
       [0.39518481, 0.66656992, 0.84202298, 0.52141464]])

In [16]:
#np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [17]:
#np.identity

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 2. Array Attributes

In [18]:
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [25]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [27]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
#ndim -> dimension of the array
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
#shape  -> shape of the array

print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
#size -> no of items 

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [23]:
# itemsize -> memory space each item takes

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [29]:
#dtype -> datatype of the array

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


## 3. Changing the datatype 

In [30]:
#astype

a3.dtype

dtype('int64')

In [32]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## 4. Array Operations

In [33]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [34]:
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
print(a2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [36]:
# Scalar operations

#arithemetic operations
a1 +2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [37]:
a2 ** 2

array([[144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [39]:
# relational operations
a2 > 5


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
# vector operations

# arithemetic

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [42]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

## 5. Array functions

In [43]:
a1  =  np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[62., 80., 73.],
       [86., 32., 41.],
       [70., 13., 90.]])

In [50]:
# max/min/sum/prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

90.0
13.0
547.0
3345959844864000.0


In [ ]:
# rowise max

np.max(a1,axis = 1)

# columnwise min

np.min(a1, axis = 0)

array([62., 13., 41.])

In [54]:
# mean/median/std/var

np.mean(a1,axis = 0)

array([72.66666667, 41.66666667, 68.        ])

In [55]:
np.median(a1)

np.float64(70.0)

In [56]:
np.std(a1)

np.float64(24.938937773769567)

In [57]:
np.var(a1)

np.float64(621.9506172839506)

In [58]:
# trignometric functions

np.sin(a1)

array([[-0.7391807 , -0.99388865, -0.67677196],
       [-0.92345845,  0.55142668, -0.15862267],
       [ 0.77389068,  0.42016704,  0.89399666]])

In [59]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [60]:
# log and exponents

a1

array([[62., 80., 73.],
       [86., 32., 41.],
       [70., 13., 90.]])

In [61]:
np.log(a1)

array([[4.12713439, 4.38202663, 4.29045944],
       [4.4543473 , 3.4657359 , 3.71357207],
       [4.24849524, 2.56494936, 4.49980967]])

In [62]:
np.exp(a1)

array([[8.43835667e+26, 5.54062238e+34, 5.05239363e+31],
       [2.23524660e+37, 7.89629602e+13, 6.39843494e+17],
       [2.51543867e+30, 4.42413392e+05, 1.22040329e+39]])

In [67]:
# round/floor/ceil

np.floor(np.random.rand(2,3)*100)

array([[70., 28., 56.],
       [ 0., 68., 94.]])

## 6. Indexing/slicing

In [72]:
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1,a2,a3, sep ='\n\n')


[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [73]:
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
#accessing 6 form a2
a2[1][2]    # -> a2[row][column]  for 2D

np.float64(6.0)

In [76]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [78]:
#to access 5 form a3 
a3[1][0][1]  # -> a3[pos of 2D array in which item exists][row][colum]

np.int64(5)

In [79]:
#slicing

print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a1[2:-1:2]  # -> same as python list

array([2, 4, 6, 8], dtype=int32)

In [84]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# 5 6 9 10
a2[1:,1:3]

array([[ 5.,  6.],
       [ 9., 10.]])

In [ ]:
# 0 3 8 11
a2[::2,::3]

array([[ 0.,  3.],
       [ 8., 11.]])

In [94]:
# 1 3 9 11

a2[::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [95]:
# 4 7
a2[1,::3]

array([4., 7.])

In [ ]:
# 1 2 3 5 6 7
a2[0:2,1:]

array([[1., 2., 3.],
       [5., 6., 7.]])

In [99]:
# 3D case
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [103]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [104]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
# 3 4 5
a3[0,1,:]

array([3, 4, 5])

In [ ]:
# 10 13 16
a3[1,:,1]

array([10, 13, 16])

In [ ]:
# 22 23 25 26
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [113]:
# 0 2 18 20

a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## 7. iterating

In [117]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

for i in a2:
    print(i)  # -> 1 row at a time in 2D

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [ ]:
a3

for i in a3:
    print(i)  # ->2D array at a time 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
# nditer converts the array in 1D and prints each item

for i in np.nditer(a3):  
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## 8. Reshaping

In [ ]:
# reshape  -> changes the shape of the array. Used earlier


In [ ]:
# Transpose
np.transpose(a2)
a2.T  # same

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [125]:
#ravel -> converts ndarray to 1D array

a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## 9. Stacking

In [ ]:
# horizontal stacking -> add columns
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hstack((a4,a5))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# vertical Stacking -> add rows
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## 10. Splitting

In [133]:
# horizontal spliting
arr = np.hstack((a4,a5))
arr

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# horizontal splitting -> splits columns
np.hsplit(arr,2)   # -> a4 in 2 parts

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [137]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# vertical splitting  -> split rows
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [2]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [3]:
a = np.zeros(10) * np.nan
a[4]=1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [4]:
a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
arr = np.random.random((a,b))
print(arr)
print("The avg is :",np.mean(arr))


[[0.23612113 0.51549984 0.35704147 0.48083288 0.97126237 0.20151986]
 [0.37542732 0.6630532  0.10874254 0.83558258 0.40144915 0.80995279]]
The avg is : 0.4963737592477199


### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [5]:
def return_2D(a,b):
    arr = np.ones((a,b))
    arr[1:-1,1:-1] = 0
    return arr

return_2D(4,4)


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [6]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [7]:
# No, for identity matrix number of rows and columns should be equal
# but the matrix with diagnoal 1's and other items 0 can be made as

np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [8]:
np.ones((5,5))*np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [9]:
arr = np.random.randint(1,100,(10,2))
print(arr)
point = np.array([2,3])

for i in arr:
    print(int(((i[0]-point[0])**2 + (i[1]-point[1])**2)**0.5))

[[39 31]
 [64 81]
 [62 50]
 [33 83]
 [77 58]
 [41 27]
 [58 71]
 [43 40]
 [75  9]
 [71 95]]
46
99
76
85
93
45
88
55
73
115


### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [10]:
a = np.arange(1,337).reshape(6,7,8)
print(a)
np.unravel_index(100,(6,7,8))

[[[  1   2   3   4   5   6   7   8]
  [  9  10  11  12  13  14  15  16]
  [ 17  18  19  20  21  22  23  24]
  [ 25  26  27  28  29  30  31  32]
  [ 33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55  56]]

 [[ 57  58  59  60  61  62  63  64]
  [ 65  66  67  68  69  70  71  72]
  [ 73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88]
  [ 89  90  91  92  93  94  95  96]
  [ 97  98  99 100 101 102 103 104]
  [105 106 107 108 109 110 111 112]]

 [[113 114 115 116 117 118 119 120]
  [121 122 123 124 125 126 127 128]
  [129 130 131 132 133 134 135 136]
  [137 138 139 140 141 142 143 144]
  [145 146 147 148 149 150 151 152]
  [153 154 155 156 157 158 159 160]
  [161 162 163 164 165 166 167 168]]

 [[169 170 171 172 173 174 175 176]
  [177 178 179 180 181 182 183 184]
  [185 186 187 188 189 190 191 192]
  [193 194 195 196 197 198 199 200]
  [201 202 203 204 205 206 207 208]
  [209 210 211 212 213 214 215 216]
  [217 218 219 220 221

(np.int64(1), np.int64(5), np.int64(4))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
a = input().strip().split()
np.array(a[::-1]).astype(float)

array([6., 5., 4., 3., 2.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
def no_of_elements(a):
    return 'elements_count : {}'.format(np.size(a))

no_of_elements(np.array([1,2]))

'elements_count : 2'

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=1}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
def softmax(a):
    if type(a) != np.ndarray:
        raise TypeError("Requires numpy array")
    elif a.ndim != 1:
        raise TypeError("Provide 1D numpy array")
    exp_a = np.exp(a)
    deno = np.sum(exp_a)
    return np.array(exp_a/deno)
        
softmax(np.array([86.03331084 ,37.7285648  ,48.64908087 ,87.16563062 ,38.40852563 ,37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
def verticles_stack(*args):
    if type(args) != np.ndarray:
        raise TypeError('Requires numpy array')
    return np.vstack(args)

a= np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])

b=np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])

print('a =', a)
print('b =', b)

verticles_stack(a,b)

a = [[0 1 2 3 4]
 [5 6 7 8 9]]
b = [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
import numpy as np
def date_array(start: str,end :str):
    if type(start) != str and type(end) != str:
        raise TypeError("Start and end date should be in format YYYY-MM-DD")

   
    end_inclusive = str(np.datetime64(end) + np.timedelta64(1, 'D'))
    return np.arange(start,end_inclusive,dtype = 'datetime64[D]')

date_array('2020-09-15','2020-09-30')

array(['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
       '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
       '2020-09-23', '2020-09-24', '2020-09-25', '2020-09-26',
       '2020-09-27', '2020-09-28', '2020-09-29', '2020-09-30'],
      dtype='datetime64[D]')

### `Q-14:` Subtract the mean of each row from a matrix.

In [11]:
x = np.random.random((5,4))
print(x)
print(x.mean(axis =1, keepdims=True))
x = x - x.mean(axis =1, keepdims=True)
print(x)

[[2.59707133e-01 6.16101591e-01 9.37363389e-01 4.84224077e-01]
 [8.10027511e-01 4.84134884e-01 1.14465995e-01 6.31335490e-01]
 [6.33606255e-01 1.70351703e-01 9.21183107e-01 4.88464749e-01]
 [5.39497325e-01 5.63848801e-01 3.22073244e-01 8.53097354e-04]
 [2.42208590e-01 1.11489706e-01 7.64916953e-01 8.89924663e-01]]
[[0.57434905]
 [0.50999097]
 [0.55340145]
 [0.35656812]
 [0.50213498]]
[[-0.31464191  0.04175254  0.36301434 -0.09012497]
 [ 0.30003654 -0.02585609 -0.39552497  0.12134452]
 [ 0.0802048  -0.38304975  0.36778165 -0.0649367 ]
 [ 0.18292921  0.20728068 -0.03449487 -0.35571502]
 [-0.25992639 -0.39064527  0.26278198  0.38778968]]


### `Q-15:` Swap column-1 of array with column-2 in the array.

In [12]:
arr = np.arange(12).reshape(3,4)
print(arr)

arr = arr[:,[1,0,2,3]]
print(arr) 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


### `Q-16:` Replace odd elements in arrays with -1.

In [13]:
arr = np.arange(12).reshape(3,4)
print(arr)
arr[arr%2 == 1] =  -1
arr


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1]])

### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [14]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

a[a < b] = b[a<b]
print(a)

[6 3 1 7 8]


### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [15]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
print(arr1)

#alternate columns
print(arr1[:,::2])

#normalization part
min = arr1.min()
max = arr1.max()

arr1  = (arr1 - min)/(max - min)

print(arr1)


[[5579 3304 5230 7852 1155]
 [ 376 1322 7303 8615 1353]
 [7804 1878 6527 5061 2254]
 [5819 9587 9327 3442 1434]
 [ 957 7391 3348 4616 5836]
 [1321 7634 9265 2018 1194]
 [7163 7839   13 4328 4008]
 [9554 9752 1026 3038  515]]
[[5579 5230 1155]
 [ 376 7303 1353]
 [7804 6527 2254]
 [5819 9327 1434]
 [ 957 3348 5836]
 [1321 9265 1194]
 [7163   13 4008]
 [9554 1026  515]]
[[0.57151658 0.3379197  0.53568128 0.8049081  0.1172605 ]
 [0.03727282 0.13440805 0.74853681 0.8832529  0.13759113]
 [0.79997946 0.1914981  0.66885717 0.51832837 0.23010576]
 [0.59615977 0.98305781 0.95636102 0.35208954 0.1459082 ]
 [0.09692987 0.75757265 0.34243762 0.47263579 0.59790533]
 [0.13430537 0.78252387 0.94999487 0.20587329 0.12126502]
 [0.73416162 0.80357326 0.         0.44306397 0.41020639]
 [0.97966937 1.         0.10401479 0.31060684 0.05154533]]


### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [16]:
def nth_largest(arr,n):
    if n>len(arr):
        raise IndexError('n should be less than the length of the array')
    
    arr.sort()
    return arr[-n]

nth_largest(np.array([12,34,40,7,1,0]),3)




np.int64(12)

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [17]:
a = np.array([1,2,3])
np.hstack([np.repeat(a,3),np.tile(a,3)])


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])