## `1.` np.sort
returns a sorted copy of an array

In [2]:
import numpy as np

a = np.random.randint(1,100,15)
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [3]:
np.sort(a)[::-1]

array([97, 95, 88, 84, 84, 79, 71, 67, 51, 43, 37, 14, 12,  1,  1],
      dtype=int32)

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[94, 39, 29, 17],
       [53, 22, 75, 38],
       [16, 39, 21, 68],
       [38, 34, 52, 99],
       [45, 66, 52, 56],
       [85, 28, 70, 97]], dtype=int32)

In [5]:
np.sort(b, axis = 0)

array([[16, 22, 21, 17],
       [38, 28, 29, 38],
       [45, 34, 52, 56],
       [53, 39, 52, 68],
       [85, 39, 70, 97],
       [94, 66, 75, 99]], dtype=int32)

## `2.` np.append

append value across mentioned axis

In [6]:
np.append(a,200)

array([ 88,  79,  84,  95,  51,   1,  12,  67,  43,  71,  84,   1,  97,
        37,  14, 200])

In [12]:
b


array([[94, 39, 29, 17],
       [53, 22, 75, 38],
       [16, 39, 21, 68],
       [38, 34, 52, 99],
       [45, 66, 52, 56],
       [85, 28, 70, 97]], dtype=int32)

In [8]:
np.append(b, np.ones((b.shape[0],1)), axis = 1)

array([[94., 39., 29., 17.,  1.],
       [53., 22., 75., 38.,  1.],
       [16., 39., 21., 68.,  1.],
       [38., 34., 52., 99.,  1.],
       [45., 66., 52., 56.,  1.],
       [85., 28., 70., 97.,  1.]])

##  `3.` np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis

In [13]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [17]:
np.concatenate((c,d), axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## `4.` np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique method()

In [18]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

## `5. ` np.expand_dims

With the help of Numpy.extend_dims() method, we can get the expanded dimensions of an array.



In [19]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [24]:
np.expand_dims(a, axis=1).shape

(15, 1)

In [25]:
np.expand_dims(a, axis=0).shape

(1, 15)

## `6. np.where` 

The numpy.where() function returns the indeces of elements in an input array where the given condition is satisfied

In [26]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [27]:
# findall indices with the value greater than 50

np.where(a>50)

(array([ 0,  1,  2,  3,  4,  7,  9, 10, 12]),)

In [ ]:
#replace all values > 50 with 0
#np.where(condition,True,False)

np.where(a>50,0,a) 

array([ 0,  0,  0,  0,  0,  1, 12,  0, 43,  0,  0,  1,  0, 37, 14],
      dtype=int32)

In [30]:
# to replace evens with 0

np.where(a%2 == 0,0,a)

array([ 0, 79,  0, 95, 51,  1,  0, 67, 43, 71,  0,  1, 97, 37,  0],
      dtype=int32)

## `7. ` np.argmax()

The numpy.argmax() function returns indices of the max element of the array in the particular axis

In [31]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [32]:
np.argmax(a)

np.int64(12)

In [33]:
b

array([[94, 39, 29, 17],
       [53, 22, 75, 38],
       [16, 39, 21, 68],
       [38, 34, 52, 99],
       [45, 66, 52, 56],
       [85, 28, 70, 97]], dtype=int32)

In [35]:
np.argmax(b, axis = 0)

array([0, 4, 1, 3])

In [37]:
# np.argmin

a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [38]:
np.argmin(a)

np.int64(5)

## `8.` np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [39]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [40]:
np.cumsum(a)

array([ 88, 167, 251, 346, 397, 398, 410, 477, 520, 591, 675, 676, 773,
       810, 824])

In [41]:
b

array([[94, 39, 29, 17],
       [53, 22, 75, 38],
       [16, 39, 21, 68],
       [38, 34, 52, 99],
       [45, 66, 52, 56],
       [85, 28, 70, 97]], dtype=int32)

In [43]:
np.cumsum(b, axis = 1)

array([[ 94, 133, 162, 179],
       [ 53,  75, 150, 188],
       [ 16,  55,  76, 144],
       [ 38,  72, 124, 223],
       [ 45, 111, 163, 219],
       [ 85, 113, 183, 280]])

In [45]:
# np.cumprod
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [46]:
np.cumprod(a)

array([                  88,                 6952,               583968,
                   55476960,           2829324960,           2829324960,
                33951899520,        2274777267840,       97815422517120,
           6944894998715520,   583371179892103680,   583371179892103680,
        1246772228405402112, -9209659770128776704,   191971734163987456])

## `9.` np.percentile

numpy.percentile() function used to compute the nth percentile of the given data (array elements) along the specified axis

In [47]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [ ]:
np.percentile(a,100)   # -> highest

np.float64(97.0)

In [ ]:
np.percentile(a,0)    # -> lowest

np.float64(1.0)

In [ ]:
np.percentile(a,50)     # -> mid

np.float64(67.0)

In [52]:
# median
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [53]:
np.median(a)

np.float64(67.0)

## `10.` np.histogram
 numpy has a built-in numpy.histogram() function which represents the frequency of the data distribution in the graphical form.

In [54]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [55]:
np.histogram(a,bins =[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 2, 0, 1, 1, 1, 1, 2, 3, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

## `11. ` np.corrcoef

return Pearson Product-moment correlation coefficients

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)   

##              salary     experince
##  salary          1           0.25
##  experience      0.25           1



array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## `12. ` np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [57]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [59]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a, items)]

array([], dtype=int32)

## `13` np.flip()
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [60]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [62]:
np.flip(a)

array([14, 37, 97,  1, 84, 71, 43, 67, 12,  1, 51, 95, 84, 79, 88],
      dtype=int32)

In [63]:
b

array([[94, 39, 29, 17],
       [53, 22, 75, 38],
       [16, 39, 21, 68],
       [38, 34, 52, 99],
       [45, 66, 52, 56],
       [85, 28, 70, 97]], dtype=int32)

In [65]:
np.flip(b, axis = 0)

array([[85, 28, 70, 97],
       [45, 66, 52, 56],
       [38, 34, 52, 99],
       [16, 39, 21, 68],
       [53, 22, 75, 38],
       [94, 39, 29, 17]], dtype=int32)

In [67]:
np.flip(b, axis = 1)

array([[17, 29, 39, 94],
       [38, 75, 22, 53],
       [68, 21, 39, 16],
       [99, 52, 34, 38],
       [56, 52, 66, 45],
       [97, 70, 28, 85]], dtype=int32)

## `14` np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flanttened array.

In [68]:
np.put(a,[0,1],[110,120] )

In [69]:
a

array([110, 120,  84,  95,  51,   1,  12,  67,  43,  71,  84,   1,  97,
        37,  14], dtype=int32)

## `15.` np.delete

The numpy.delete() function returns a new array with the deletion of subarrays along with the mentioned axis.

In [70]:
a

array([110, 120,  84,  95,  51,   1,  12,  67,  43,  71,  84,   1,  97,
        37,  14], dtype=int32)

In [72]:
np.delete(a,[0,2,4])

array([120,  95,   1,  12,  67,  43,  71,  84,   1,  97,  37,  14],
      dtype=int32)

## `16.` Set functions
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [73]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])


In [74]:
m

array([1, 2, 3, 4, 5])

In [75]:
n

array([3, 4, 5, 6, 7])

In [76]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [77]:
np.intersect1d(m,n)

array([3, 4, 5])

In [78]:
np.setdiff1d(m,n)

array([1, 2])

In [79]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [82]:
m[np.in1d(m,3)]

C:\Users\lokes\AppData\Local\Temp\ipykernel_17528\2281026980.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,3)]


array([3])

## `17.` np.clip

numpy.clip() function is used to clip (limit) the values in an array

In [83]:
a

array([110, 120,  84,  95,  51,   1,  12,  67,  43,  71,  84,   1,  97,
        37,  14], dtype=int32)

In [84]:
np.clip(a,a_max = 75,a_min = 25)

array([75, 75, 75, 75, 51, 25, 25, 67, 43, 71, 75, 25, 75, 37, 25],
      dtype=int32)