## `1.` np.sort
returns a sorted copy of an array

In [2]:
import numpy as np

a = np.random.randint(1,100,15)
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [3]:
np.sort(a)[::-1]

array([97, 95, 88, 84, 84, 79, 71, 67, 51, 43, 37, 14, 12,  1,  1],
      dtype=int32)

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[94, 39, 29, 17],
       [53, 22, 75, 38],
       [16, 39, 21, 68],
       [38, 34, 52, 99],
       [45, 66, 52, 56],
       [85, 28, 70, 97]], dtype=int32)

In [5]:
np.sort(b, axis = 0)

array([[16, 22, 21, 17],
       [38, 28, 29, 38],
       [45, 34, 52, 56],
       [53, 39, 52, 68],
       [85, 39, 70, 97],
       [94, 66, 75, 99]], dtype=int32)

## `2.` np.append

append value across mentioned axis

In [6]:
np.append(a,200)

array([ 88,  79,  84,  95,  51,   1,  12,  67,  43,  71,  84,   1,  97,
        37,  14, 200])

In [12]:
b


array([[94, 39, 29, 17],
       [53, 22, 75, 38],
       [16, 39, 21, 68],
       [38, 34, 52, 99],
       [45, 66, 52, 56],
       [85, 28, 70, 97]], dtype=int32)

In [8]:
np.append(b, np.ones((b.shape[0],1)), axis = 1)

array([[94., 39., 29., 17.,  1.],
       [53., 22., 75., 38.,  1.],
       [16., 39., 21., 68.,  1.],
       [38., 34., 52., 99.,  1.],
       [45., 66., 52., 56.,  1.],
       [85., 28., 70., 97.,  1.]])

##  `3.` np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis

In [13]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [17]:
np.concatenate((c,d), axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## `4.` np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique method()

In [18]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

## `5. ` np.expand_dims

With the help of Numpy.extend_dims() method, we can get the expanded dimensions of an array.



In [19]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [24]:
np.expand_dims(a, axis=1).shape

(15, 1)

In [25]:
np.expand_dims(a, axis=0).shape

(1, 15)

## `6. np.where` 

The numpy.where() function returns the indeces of elements in an input array where the given condition is satisfied

In [26]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [27]:
# findall indices with the value greater than 50

np.where(a>50)

(array([ 0,  1,  2,  3,  4,  7,  9, 10, 12]),)

In [ ]:
#replace all values > 50 with 0
#np.where(condition,True,False)

np.where(a>50,0,a) 

array([ 0,  0,  0,  0,  0,  1, 12,  0, 43,  0,  0,  1,  0, 37, 14],
      dtype=int32)

In [30]:
# to replace evens with 0

np.where(a%2 == 0,0,a)

array([ 0, 79,  0, 95, 51,  1,  0, 67, 43, 71,  0,  1, 97, 37,  0],
      dtype=int32)

## `7. ` np.argmax()

The numpy.argmax() function returns indices of the max element of the array in the particular axis

In [31]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [32]:
np.argmax(a)

np.int64(12)

In [33]:
b

array([[94, 39, 29, 17],
       [53, 22, 75, 38],
       [16, 39, 21, 68],
       [38, 34, 52, 99],
       [45, 66, 52, 56],
       [85, 28, 70, 97]], dtype=int32)

In [35]:
np.argmax(b, axis = 0)

array([0, 4, 1, 3])

In [37]:
# np.argmin

a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [38]:
np.argmin(a)

np.int64(5)

## `8.` np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [39]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [40]:
np.cumsum(a)

array([ 88, 167, 251, 346, 397, 398, 410, 477, 520, 591, 675, 676, 773,
       810, 824])

In [41]:
b

array([[94, 39, 29, 17],
       [53, 22, 75, 38],
       [16, 39, 21, 68],
       [38, 34, 52, 99],
       [45, 66, 52, 56],
       [85, 28, 70, 97]], dtype=int32)

In [43]:
np.cumsum(b, axis = 1)

array([[ 94, 133, 162, 179],
       [ 53,  75, 150, 188],
       [ 16,  55,  76, 144],
       [ 38,  72, 124, 223],
       [ 45, 111, 163, 219],
       [ 85, 113, 183, 280]])

In [45]:
# np.cumprod
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [46]:
np.cumprod(a)

array([                  88,                 6952,               583968,
                   55476960,           2829324960,           2829324960,
                33951899520,        2274777267840,       97815422517120,
           6944894998715520,   583371179892103680,   583371179892103680,
        1246772228405402112, -9209659770128776704,   191971734163987456])

## `9.` np.percentile

numpy.percentile() function used to compute the nth percentile of the given data (array elements) along the specified axis

In [47]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [ ]:
np.percentile(a,100)   # -> highest

np.float64(97.0)

In [ ]:
np.percentile(a,0)    # -> lowest

np.float64(1.0)

In [ ]:
np.percentile(a,50)     # -> mid

np.float64(67.0)

In [52]:
# median
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [53]:
np.median(a)

np.float64(67.0)

## `10.` np.histogram
 numpy has a built-in numpy.histogram() function which represents the frequency of the data distribution in the graphical form.

In [54]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [55]:
np.histogram(a,bins =[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 2, 0, 1, 1, 1, 1, 2, 3, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

## `11. ` np.corrcoef

return Pearson Product-moment correlation coefficients

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)   

##              salary     experince
##  salary          1           0.25
##  experience      0.25           1



array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## `12. ` np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [57]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [59]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a, items)]

array([], dtype=int32)

## `13` np.flip()
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [60]:
a

array([88, 79, 84, 95, 51,  1, 12, 67, 43, 71, 84,  1, 97, 37, 14],
      dtype=int32)

In [62]:
np.flip(a)

array([14, 37, 97,  1, 84, 71, 43, 67, 12,  1, 51, 95, 84, 79, 88],
      dtype=int32)

In [63]:
b

array([[94, 39, 29, 17],
       [53, 22, 75, 38],
       [16, 39, 21, 68],
       [38, 34, 52, 99],
       [45, 66, 52, 56],
       [85, 28, 70, 97]], dtype=int32)

In [65]:
np.flip(b, axis = 0)

array([[85, 28, 70, 97],
       [45, 66, 52, 56],
       [38, 34, 52, 99],
       [16, 39, 21, 68],
       [53, 22, 75, 38],
       [94, 39, 29, 17]], dtype=int32)

In [67]:
np.flip(b, axis = 1)

array([[17, 29, 39, 94],
       [38, 75, 22, 53],
       [68, 21, 39, 16],
       [99, 52, 34, 38],
       [56, 52, 66, 45],
       [97, 70, 28, 85]], dtype=int32)

## `14` np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flanttened array.

In [68]:
np.put(a,[0,1],[110,120] )

In [69]:
a

array([110, 120,  84,  95,  51,   1,  12,  67,  43,  71,  84,   1,  97,
        37,  14], dtype=int32)

## `15.` np.delete

The numpy.delete() function returns a new array with the deletion of subarrays along with the mentioned axis.

In [70]:
a

array([110, 120,  84,  95,  51,   1,  12,  67,  43,  71,  84,   1,  97,
        37,  14], dtype=int32)

In [72]:
np.delete(a,[0,2,4])

array([120,  95,   1,  12,  67,  43,  71,  84,   1,  97,  37,  14],
      dtype=int32)

## `16.` Set functions
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [73]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])


In [74]:
m

array([1, 2, 3, 4, 5])

In [75]:
n

array([3, 4, 5, 6, 7])

In [76]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [77]:
np.intersect1d(m,n)

array([3, 4, 5])

In [78]:
np.setdiff1d(m,n)

array([1, 2])

In [79]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [82]:
m[np.in1d(m,3)]

C:\Users\lokes\AppData\Local\Temp\ipykernel_17528\2281026980.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,3)]


array([3])

## `17.` np.clip

numpy.clip() function is used to clip (limit) the values in an array

In [83]:
a

array([110, 120,  84,  95,  51,   1,  12,  67,  43,  71,  84,   1,  97,
        37,  14], dtype=int32)

In [84]:
np.clip(a,a_max = 75,a_min = 25)

array([75, 75, 75, 75, 51, 25, 25, 67, 43, 71, 75, 25, 75, 37, 25],
      dtype=int32)

## ---------------- Questions --------------------------

### `Q-1:` Create a random 4x3 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [ ]:
import numpy as np

arr = np.random.randint(1,100,(4,3))
arr

array([[70, 29,  7],
       [31, 53, 57],
       [43, 10,  8],
       [ 4, 46, 60]], dtype=int32)

In [ ]:
# i
np.sort(arr)

array([[27, 80, 87],
       [46, 56, 95],
       [ 3, 14, 75],
       [33, 49, 49]], dtype=int32)

In [ ]:
# ii
# to sort the array according to 2nd column
arr[arr[:,1].argsort()]

array([[49, 49, 33],
       [ 3, 75, 14],
       [87, 80, 27],
       [46, 95, 56]], dtype=int32)

In [ ]:
## II
# sort the array with the key as the maximum value of each row
np.array(sorted(arr, key= lambda x : max(x)))


array([[49, 49, 33],
       [ 3, 75, 14],
       [87, 80, 27],
       [46, 95, 56]], dtype=int32)

In [ ]:
### iv
# converts into D and sort the items the reshape to 4*3
np.sort(arr, axis = None).reshape(4,3)


array([[ 3, 14, 27],
       [33, 46, 49],
       [49, 56, 75],
       [80, 87, 95]], dtype=int32)

### `Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [ ]:
marks =np.array( [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

extra_subject =np.array([41, 87, 72, 36, 92]).reshape(-1,1)

In [ ]:
#i 
marks = np.concatenate([marks,extra_subject], axis =1)
marks


array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [ ]:
# ii
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,-1)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,-1)

marks = np.concatenate([marks,rec1,rec2], axis = 0)
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [ ]:
# iii 
total_marks = np.sum(marks, axis =1).reshape(-1,1)

marks = np.concatenate([marks,total_marks], axis = 1)
marks


array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [ ]:
# iv
print(marks[marks[:,-1].argsort()][::-1])

[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]
 [ 63  46  90  42  87 328]
 [ 67  61  59  36  92 315]
 [ 82   9  29  78  36 234]
 [ 39  76  13  29  72 229]
 [ 13  10   9  33  41 106]]


### `Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
# Rowwise
print(np.unique(arr, axis=0))

# ColumnWise
print(np.unique(arr, axis = 1))

[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


### `Q-4:` Flip given 2-D array along both axes at the same time.

In [ ]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

np.flip(arr, axis = [0,1])


array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [ ]:
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])

x = 6

np.where(np.any(arr>x, axis = 1))

(array([1, 3]),)

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [ ]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [ ]:
np.concatenate([arr1, arr2, arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [ ]:
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print(arr)

max_pos = arr.argmax()
min_pos = arr.argmin()
print(np.max(arr),np.min(arr))
arr = np.delete(arr,[max_pos,min_pos])
print(np.max(arr),np.min(arr))




[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]
998 103
997 117


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [ ]:
arr =  np.random.randint(100,700,200)
np.cumsum(np.sort(np.clip(arr, 100,200)))

array([  101,   203,   305,   408,   511,   615,   721,   828,   938,
        1049,  1160,  1273,  1388,  1503,  1620,  1759,  1902,  2045,
        2188,  2332,  2480,  2631,  2791,  2955,  3120,  3298,  3482,
        3671,  3860,  4052,  4244,  4437,  4631,  4826,  5022,  5220,
        5420,  5620,  5820,  6020,  6220,  6420,  6620,  6820,  7020,
        7220,  7420,  7620,  7820,  8020,  8220,  8420,  8620,  8820,
        9020,  9220,  9420,  9620,  9820, 10020, 10220, 10420, 10620,
       10820, 11020, 11220, 11420, 11620, 11820, 12020, 12220, 12420,
       12620, 12820, 13020, 13220, 13420, 13620, 13820, 14020, 14220,
       14420, 14620, 14820, 15020, 15220, 15420, 15620, 15820, 16020,
       16220, 16420, 16620, 16820, 17020, 17220, 17420, 17620, 17820,
       18020, 18220, 18420, 18620, 18820, 19020, 19220, 19420, 19620,
       19820, 20020, 20220, 20420, 20620, 20820, 21020, 21220, 21420,
       21620, 21820, 22020, 22220, 22420, 22620, 22820, 23020, 23220,
       23420, 23620,

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [ ]:
arr = np.random.random(100)
print(arr)
arr = np.around(arr,3)
print(arr)
print("0th percentile == minimum value of the array :", np.min(arr) == np.percentile(arr,0))

print("100th percentile == maximum value of the array :", np.max(arr) == np.percentile(arr,100))

print("the difference betwen 51th percenile and 50th percentile values :", np.percentile(arr,51)- np.percentile(arr,50))

[0.78486115 0.62783633 0.77104419 0.625664   0.71500075 0.19978724
 0.91420766 0.05986098 0.12500474 0.07185441 0.05794639 0.33052932
 0.36991397 0.69558883 0.2146413  0.98938328 0.40819305 0.56502608
 0.46706852 0.92761878 0.53156583 0.73619213 0.01702467 0.01761888
 0.22653295 0.27911904 0.00755887 0.77839236 0.62452036 0.38018724
 0.90368799 0.89694098 0.02294569 0.96874712 0.14135078 0.1071127
 0.96269857 0.01192734 0.94894953 0.89541047 0.15415909 0.52434461
 0.71439654 0.03502903 0.2547694  0.10928692 0.8432518  0.85090731
 0.26862735 0.69859792 0.69199303 0.9240665  0.81639562 0.10791593
 0.2269286  0.18765571 0.25909058 0.07218158 0.7152535  0.53235615
 0.35026807 0.25597634 0.28033645 0.54735748 0.59246386 0.35707361
 0.36282235 0.22128719 0.03754857 0.89119857 0.64234499 0.96775545
 0.63841299 0.20821918 0.94868947 0.32784577 0.78261874 0.77793021
 0.0927639  0.65419945 0.14907459 0.24151976 0.71331728 0.06223032
 0.40964621 0.01933893 0.88157932 0.23588887 0.8825726  0.02371