# 100 numpy exercises

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as  np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
np.__version__
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/lokes/anaconda3/Library/include
    lib directory: C:/Users/lokes/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cpu: 

#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [8]:
z=np.zeros((10,10))
print(f"{z.size*z.itemsize} bytes")

800 bytes


#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [9]:
z=np.zeros(10)
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 

In [11]:
z=np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [12]:
z=np.arange(50)
z=z[::-1]
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
z=np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [16]:
nz=np.nonzero( [1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
z=np.random.random((3,3,3))
z

array([[[0.40751165, 0.98778674, 0.06130887],
        [0.23635317, 0.69708951, 0.83518111],
        [0.64217839, 0.71339406, 0.24705653]],

       [[0.97702581, 0.96316424, 0.56122094],
        [0.44391467, 0.26964746, 0.75537822],
        [0.84885349, 0.90833377, 0.42639824]],

       [[0.60394924, 0.42555514, 0.50095722],
        [0.51209942, 0.57324228, 0.59532473],
        [0.9653065 , 0.25152235, 0.09295368]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [21]:
z=np.random.random((10,10))
print(z)
print(f"max value = {z.max()}")
print(f"min value = {z.min()}")

[[0.86951404 0.89427021 0.65932731 0.70395105 0.02115838 0.23863677
  0.48310885 0.959718   0.04521318 0.69051782]
 [0.22782953 0.28943554 0.27996956 0.32648569 0.75010232 0.60140504
  0.69950762 0.55058945 0.37761962 0.43083156]
 [0.059571   0.14895012 0.86616424 0.69002122 0.28792198 0.36113051
  0.629706   0.38314572 0.5897268  0.20241112]
 [0.35124717 0.75245797 0.39151505 0.40980317 0.9321003  0.31324922
  0.38211072 0.2293387  0.31075974 0.01387148]
 [0.58034393 0.01109313 0.34977434 0.10379813 0.44750186 0.09995992
  0.1447753  0.52134605 0.60103194 0.16926453]
 [0.44002693 0.68299977 0.0658288  0.46458762 0.77085618 0.85803333
  0.80878421 0.11632454 0.54669414 0.37153924]
 [0.83918268 0.31967451 0.6753762  0.72801765 0.81775752 0.99188953
  0.63796367 0.59553844 0.09583187 0.09631274]
 [0.87140716 0.98172421 0.23435377 0.93559034 0.78584339 0.10156294
  0.71372018 0.54516648 0.30384684 0.62474085]
 [0.95351842 0.29751876 0.76392227 0.75786563 0.13066417 0.64195222
  0.20384124

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [24]:
z=np.random.random(30)
print(z)
print(f"mean = {z.mean()}")

[0.1898686  0.80828917 0.78478156 0.39000996 0.39413674 0.55205256
 0.52251999 0.13982579 0.75929118 0.47436892 0.94986668 0.31406602
 0.04873311 0.80631005 0.216513   0.19440804 0.98471233 0.72920439
 0.83680213 0.91382313 0.76260461 0.00277164 0.42452392 0.56339147
 0.14781952 0.96248641 0.30037233 0.5140085  0.5748335  0.93576232]
mean = 0.5399385856311282


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [27]:
z=np.ones((10,10))
z[1:-1,1:-1]=0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [29]:
z=np.ones((5,5))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

In [30]:
    print(0 * np.nan) # Any arithmetic with NaN(not a number) results Nan
    print(np.nan == np.nan)  #false ,, by defination NaN is not equal to anything
    print(np.inf > np.nan)  #Comparison with NaN are always false
    print(np.nan - np.nan)  #Any arithmetic with NaN(not a number) results Nan
    print(0.3 == 3 * 0.1)   #0.3 is stored as 0.2999999999999999889...     3 * 0.1 is stored as 0.3000000000000000444...   so false

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [34]:
z=np.diag(1+np.arange(4),k=-1)  #np.diag(v, k) creates a diagonal matrix with v on the k-th diagonal.
z 

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [37]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [38]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)